### ISSUE TITLE
`rtlib.Table`を使っているコグをリロードするとバグるかもしれない。

### ISSUE THREAD

**Issue by gx1285** [SakuraProject/rt-bot#13]
題名通り。
またバグるのはPythonの可能性もある。前に一度認証をリロードしたりした際に同じ辞書なのに片方からしか変更を加えられない。
そしてもう片方からデータにアクセスすると両方のデータのidが変わる。
というバグが発生してしまった。
(が、これはもしかしたら認証のViewがbot内に残ってしまっている状態でリロードされたために起きたという可能性もある)

**Comment by yaakiyu** [comment]
rtlib.Tableは今後使う予定も直す予定もないのでclose。

**Comment by tasuren** [comment]
まった、
> (が、これはもしかしたら認証のViewがbot内に残ってしまっている状態でリロードされたために起きたという可能性もある)

これ確かめれば？

**Comment by yaakiyu** [comment]
あ、確かに

**Comment by yaakiyu** [comment]
認証に関する調査するからreopenするか
