### ISSUE TITLE
Dockerの導入

### ISSUE THREAD

**Issue by kousakirai** [SakuraProject/rt-bot#131]
個人的に開発するときにMysqlを準備しないといけないのが面倒だから、できればDockerに対応させて、MysqlとBotを同時に起動できるようにしたい

**Comment by kousakirai** [comment]
それさえ可能なら、開発を本格的にできそう

**Comment by ysmreg** [comment]
mysql.serviceを作成してパソコンを起動したときに自動起動にしたほうが良さそう。mysqlのデータ量増えると起動に時間がかかるし

**Comment by kousakirai** [comment]
そうなってくるとDevとProdに分けてしたほうがよさそうだな

**Comment by yaakiyu** [comment]
ワターシdockerワーカリマセーン(外人風
