### ISSUE TITLE
レベルランキングのバグ

### ISSUE THREAD

**Issue by gx1285** [SakuraProject/rt-bot#5]
⑴表示バグ
1.0ページってなんだよ...()
あとページ数めくれないし
(2)レベルバグ
表示されてるのがレベルか経験値かわからん。単位つけよう

**Comment by tasuren** [comment]
> 1.0ページってなんだよ...()

一ページの半分内容がある場合は`0.5`になる。つまり文字通り「1.0ページ」
だから、1.4ページとかになることもある。

**Comment by tasuren** [comment]
> 表示されてるのがレベルか経験値かわからん。単位つけよう

恐らくレベル
