### ISSUE TITLE
helpの実装変更

### ISSUE THREAD

**Issue by yaakiyu** [SakuraProject/rt-bot#76]
新RTにて発見。
helpのセレクトメニューが初期状態のときは「カテゴリー」のみ表示されるようになり、
タイムアウトした際にはしっかり使えないように編集するようになっていた。
あとrtaのhelpに「RTEvent」なるものを見つけた。RTのコマンド実行ログに関連するようだ。
しかしrtaの実際のログを見ていないので詳細がわからん。

**Comment by tuna2134** [comment]
tasurenに許可もらってからにして

**Comment by yaakiyu** [comment]
helpにオートコンプリート実装を発見。これに関してはめんどくさいからしばらく実装しないで「差別化」になりそう。

**Comment by tuna2134** [comment]
実装者です。どうも

**Comment by yaakiyu** [comment]
初期状態では「カテゴリー」のみ表示するようにできた。

**Comment by tuna2134** [comment]
> 初期状態では「カテゴリー」のみ表示するようにできた。

オートコンプリート？

**Comment by yaakiyu** [comment]
オートコンプリートはしばらく実装しないつもり。

**Comment by yaakiyu** [comment]
いつの間にか変わってた。
タイムアウトしたらviewが消えるようになってた
