### ISSUE TITLE
RTWSの仕様変更

### ISSUE THREAD

**Issue by tuna2134** [SakuraProject/rt-bot#90]
まずwebsocketを一つにする

**Comment by tuna2134** [comment]
"t"にイベントタイプ
"d"にデータ

**Comment by yaakiyu** [comment]
webRTCとwebsocketって別物だからね
(RTCってなんじゃいって思っていま調べたから僕も今知ったんだけど())

**Comment by tasuren** [comment]
Rocations作る前くらいにRTWS (RT WebSocket) に被るから改名した。
だから、今はFreeRTもRTCじゃなくてRTWSね。

**Comment by yaakiyu** [comment]
rtcってRT固有名詞だったのか
